### PR TITLE
Windows: Enable EH Continuation Metadata, update

### PR DESCRIPTION
**Pull request by JeromeMartinez**

### CODE REVIEW

**Comment by cjee21** [comment]
CFG was only enabled for ReleaseWithoutAsm and not Release.

**Comment by JeromeMartinez** [comment]
> CFG was only enabled for ReleaseWithoutAsm and not Release.

I add it to Release, for not forgetting in/when we use ASM.

**Comment by cjee21** [comment]
> for not forgetting in/when we use ASM.

Noticed the MediaInfoLib ARM/ARM64 is configured to use zlib Release, not ReleaseWithoutAsm.

---

@JeromeMartinez for consistency, need check and enable CFG and EHCONT for ARM(64) in the various projects/repos also.

**Comment by JeromeMartinez** [comment]
> @JeromeMartinez for consistency, need check and enable CFG and EHCONT for ARM(64) in the various projects/repos also.

cc @g-maxime

**Pull request merged**
